apiVersion: v1
kind: Namespace
metadata:
  name: ingress-controller
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lb-controller-config
  namespace: ingress-controller
data:
  LB_APPLIANCE_IP: "<Primary loadbalancer IP>"
  VIP_POOL: "<Pool of IP's>"
  LB_USER: "loadbalancer"
